### ISSUE TITLE
 Invalid notification (no valid small icon)

### ISSUE THREAD

**Issue by smart** [phiamo/capacitor-plugin-playlist#86]
Hi there, I've got no Android experience but trying to get this up and running. The plugin is working great on ios and web. I got things building, then was facing issues with HLS, which I made progress on by adding `implementation 'com.google.android.exoplayer:exoplayer-hls:2.9.6'` to build.gradle. The issue I'm facing now is this (no valid small icon), maybe it's something stupid on my end. Happy to add you to my project, harder for me to make an MR. Will keep diving in but any guidence could be helpful. I tried using this as well. 

```
await Playlist.setOptions({
  verbose: !environment.production,
  options: {
    icon: 'ic_notification'
  },
}); 

```

state [0.07, 0.00, window=0, false, BUFFERING]
2024-04-05 18:17:44.752 10432-10432 onPlaybackStateChanged  my.app.package                     I  PREPARING, {"trackId":"6d2fc018-91e4-43e9-bc72-368cb1237725","isStream":true,"currentIndex":0,"status":"loading","currentPosition":0,"duration":0,"playbackPercent":0,"bufferPercent":0,"bufferStart":0,"bufferEnd":0}, org.dwbn.plugins.playlist.data.AudioTrack@ff577c7
2024-04-05 18:17:44.753 10432-10432 PlaylistStatusCallback  my.app.package                      V  statusChanged:{"action":"status","status":{"msgType":10,"trackId":"6d2fc018-91e4-43e9-bc72-368cb1237725","value":{"trackId":"6d2fc018-91e4-43e9-bc72-368cb1237725","isStream":true,"currentIndex":0,"status":"loading","currentPosition":0,"duration":0,"playbackPercent":0,"bufferPercent":0,"bufferStart":0,"bufferEnd":0}}}
2024-04-05 18:17:44.753 10432-10432 Capacitor/...listPlugin my.app.package                       V  Notifying listeners for event status
2024-04-05 18:17:44.754 10432-10432 my.app.package          my.app.package                   E  Invalid ID 0x00000000.
2024-04-05 18:17:44.758 10432-10432 AndroidRuntime          my.app.package                       D  Shutting down VM
2024-04-05 18:17:44.759 10432-10432 AndroidRuntime          my.app.package                       E  FATAL EXCEPTION: main
                                                                                                    Process: my.app.package , PID: 10432
                                                                                                    java.lang.RuntimeException: Unable to start service org.dwbn.plugins.playlist.service.MediaService@d813ede with Intent { act=com.devbrackets.android.playlistcore.start_service cmp=my.app.package/org.dwbn.plugins.playlist.service.MediaService (has extras) }: java.lang.IllegalArgumentException: Invalid notification (no valid small icon): Notification(channel=PlaylistCoreMediaNotificationChannel shortcut=null contentView=null vibrate=null sound=null defaults=0x0 flags=0x10 color=0x00000000 category=transport actions=3 vis=PUBLIC)
                                                                                                    	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4724)
                                                                                                    	at android.app.ActivityThread.access$2000(ActivityThread.java:256)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2129)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7870)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
                                                                                                    Caused by: java.lang.IllegalArgumentException: Invalid notification (no valid small icon): Notification(channel=PlaylistCoreMediaNotificationChannel shortcut=null contentView=null vibrate=null sound=null defaults=0x0 flags=0x10 color=0x00000000 category=transport actions=3 vis=PUBLIC)
                                                                                                    	at android.app.NotificationManager.fixNotification(NotificationManager.java:705)
                                                                                                    	at android.app.NotificationManager.notifyAsUser(NotificationManager.java:684)
                                                                                                    	at android.app.NotificationManager.notify(NotificationManager.java:633)
                                                                                                    	at android.app.NotificationManager.notify(NotificationManager.java:609)
                                                                                                    	at com.devbrackets.android.playlistcore.components.playlisthandler.DefaultPlaylistHandler.updateMediaControls(DefaultPlaylistHandler.kt:313)
                                                                                                    	at org.dwbn.plugins.playlist.playlist.AudioPlaylistHandler.updateMediaControls(AudioPlaylistHandler.java:145)
                                                                                                    	at com.devbrackets.android.playlistcore.components.playlisthandler.DefaultPlaylistHandler.setPlaybackState(DefaultPlaylistHandler.kt:522)
                                                                                                    	at com.devbrackets.android.playlistcore.components.playlisthandler.DefaultPlaylistHandler.play(DefaultPlaylistHandler.kt:440)
                                                                                                    	at com.devbrackets.android.playlistcore.components.playlisthandler.DefaultPlaylistHandler.startItemPlayback(DefaultPlaylistHandler.kt:391)
                                                                                                    	at com.devbrackets.android.playlistcore.service.BasePlaylistService.handleRemoteAction(BasePlaylistService.kt:154)
                                                                                                    	at com.devbrackets.android.playlistcore.service.BasePlaylistService.onStartCommand(BasePlaylistService.kt:133)
                                                                                                    	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4706)
                                                                                                    	at android.app.ActivityThread.access$2000(ActivityThread.java:256) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2129) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201) 
                                                                                                    	at android.os.Looper.loop(Looper.java:288) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7870) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003) 
2024-04-05 18:17:44.837 10432-10432 Process                 my.app.package                      I  Sending signal. PID: 10432 SIG: 9

**Comment by phiamo** [comment]
there is an closed issue describing a solution
